ItemLendSystemV01/Models/db_ItemLendSystem.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemLendSystemV01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItemLendSystemEntities1 : DbContext
    {
        public ItemLendSystemEntities1()
            : base("name=ItemLendSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_lend_items> t_lend_items { get; set; }
    }
}

ItemLendSystemV01/Models/db_ItemLendSystem.Designer.cs
// T4 コード生成がモデル 'C:\Users\PC_User\source\repos\ItemLendSystemV01\ItemLendSystemV01\Models\db_ItemLendSystem.edmx' に対して有効です。 
// レガシ コード生成を有効にするには、'コード生成方法' デザイナー
// プロパティの値を 'レガシ ObjectContext' に変更します。このプロパティは、デザイナーでモデルが開かれている場合に [プロパティ] ウィンドウ
// で使用できます。

// 生成されたコンテキストおよびエンティティ クラスがない場合、空のモデルを作成したが、使用する Entity Framework の
// バージョンをまだ選択していないための可能性があります。モデルのコンテキスト クラスおよび
// エンティティ クラスを生成するには、デザイナーでモデルを開いてデザイナー画面を右クリックし、
// [データベースからモデルを更新]、[モデルからデータベースを生成]、または [コード生成項目の
// 追加] を選択します。

ItemLendSystemV01/Models/db_ItemLendSystem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

ItemLendSystemV01/Models/t_lend_items.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemLendSystemV01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lend_items
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string BorowerName { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public Nullable<System.DateTime> ReturnDateExpected { get; set; }
        public Nullable<System.DateTime> ReturnDateActual { get; set; }
    }
}

ItemLendSystemV01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ItemLendSystemV01.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ItemLendSystemV01/Controllers/LendListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ItemLendSystemV01.Models;

namespace ItemLendSystemV01.Controllers
{
    public class LendListController : Controller
    {
        private ItemLendSystemEntities1 db = new ItemLendSystemEntities1();

        // GET: LendList
        public ActionResult Index()
        {
            return View(db.t_lend_items.ToList());
        }
        
        // GET: LendList/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            t_lend_items t_lend_items = db.t_lend_items.Find(id);
            if (t_lend_items == null)
            {
                return HttpNotFound();
            }
            return View(t_lend_items);
        }

        // GET: LendList/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LendList/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemID,ItemName")] t_lend_items t_lend_items)
        {
            if (ModelState.IsValid)
            {
                db.t_lend_items.Add(t_lend_items);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(t_lend_items);
        }

        // GET: LendList/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            t_lend_items t_lend_items = db.t_lend_items.Find(id);
            if (t_lend_items == null)
            {
                return HttpNotFound();
            }
            return View(t_lend_items);
        }

        // POST: LendList/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemID,ItemName,BorowerName,CheckoutDate,ReturnDateExpected,ReturnDateActual")] t_lend_items t_lend_items)
        {
            if (ModelState.IsValid)
            {
                db.Entry(t_lend_items).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(t_lend_items);
        }

        // GET: LendList/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            t_lend_items t_lend_items = db.t_lend_items.Find(id);
            if (t_lend_items == null)
            {
                return HttpNotFound();
            }
            return View(t_lend_items);
        }

        // POST: LendList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            t_lend_items t_lend_items = db.t_lend_items.Find(id);
            db.t_lend_items.Remove(t_lend_items);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ItemLendSystemV01/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ItemLendSystemV01/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ItemLendSystemV01/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ItemLendSystemV01/Views/LendList/Create.cshtml
@model ItemLendSystemV01.Models.t_lend_items

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>t_lend_items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ItemID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ItemLendSystemV01/Views/LendList/Delete.cshtml
@model ItemLendSystemV01.Models.t_lend_items

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>t_lend_items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BorowerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BorowerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckoutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckoutDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDateExpected)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDateExpected)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDateActual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDateActual)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ItemLendSystemV01/Views/LendList/Details.cshtml
@model ItemLendSystemV01.Models.t_lend_items

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>t_lend_items</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BorowerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BorowerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckoutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckoutDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDateExpected)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDateExpected)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDateActual)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDateActual)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ItemID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ItemLendSystemV01/Views/LendList/Edit.cshtml
@model ItemLendSystemV01.Models.t_lend_items

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>t_lend_items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BorowerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BorowerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BorowerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckoutDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckoutDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckoutDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDateExpected, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDateExpected, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDateExpected, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDateActual, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDateActual, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDateActual, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ItemLendSystemV01/Views/LendList/Index.cshtml
@model IEnumerable<ItemLendSystemV01.Models.t_lend_items>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BorowerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckoutDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDateExpected)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDateActual)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BorowerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckoutDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnDateExpected)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnDateActual)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ItemID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ItemID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ItemID })
        </td>
    </tr>
}

</table>

ItemLendSystemV01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - マイ ASP.NET アプリケーション</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("アプリケーション名", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ホーム", "Index", "Home")</li>
                    <li>@Html.ActionLink("貸出管理", "Index", "LendList")</li>
                    <li>@Html.ActionLink("問い合わせ", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - マイ ASP.NET アプリケーション</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>